project:
  type: website
  output-dir: docs

website:
  title: "The Little Things"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AkshayAJoseph
      - icon: linkedin
        href: https://www.linkedin.com/in/akshay-joseph-668b49285/
format:
  html:
    theme: solar
    css: styles.css



